version: '3.8'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - galtea-data:/app/db
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped

volumes:
  galtea-data:
    name: galtea-data 